# Name for the workflow, which will be displayed in the "Actions" tab of your GitHub repository
name: Publish Docker Image to Docker Hub

# This workflow runs on any push to the "master" branch
on:
  push:
    branches:
      - main

jobs:
  # Define a single job called "build_and_push"
  build_and_push:
    # This job will run on the latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository's code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Make sure to check out submodules, as the TON repository requires them
          submodules: recursive

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          # Use secrets to store your Docker Hub credentials securely
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # The context is the root of your repository
          context: .
          # The name of the Dockerfile to use for building
          file: ./Dockerfile
          # Push the image to the registry after a successful build
          push: true
          # The tag for your image (e.g., mhbdev/ton-tools:latest)
          tags: mhbdev/ton-tools:latest
