name: Publish Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    # 1. Use a more powerful runner
    runs-on: ubuntu-latest-4-cores
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
            
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mhbdev/ton-tools
          tags: |
            type=sha,prefix=
            type=raw,value=latest
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # 2. Use the modern, integrated GHA cache for BuildKit
          cache-to: type=gha,mode=max
          cache-from: type=gha
